version: '3'

services:
  web:
    build:
      context: ../ # Контекст сборки — корневая директория
      dockerfile: docker/Dockerfile
    container_name: lion_drive_client_app_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app # Монтируем директорию с исходным кодом
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - '5432:5430'
    environment:
      POSTGRES_DB: lion_drive_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: null