# Generated by Django 5.1.4 on 2024-12-15 18:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_class', models.CharField(choices=[('SUV', 'Внедорожник'), ('SPORTS', 'Спорткар'), ('PREMIUM', 'Премиум'), ('BUSINESS', 'Бизнес'), ('MINIVAN', 'Минивэн'), ('COMFORT', 'Комфорт'), ('ELECTRIC_CAR', 'Электромобиль'), ('CONVERTIBLE', 'Кабриолет')], default='COMFORT', max_length=15, verbose_name='Класс автомобиля')),
                ('engine_type', models.CharField(choices=[('GASOLINE', 'Бензиновый'), ('DIESEL', 'Дизельный'), ('ELECTRIC', 'Электрический'), ('HYBRID', 'Гибридный'), ('HYDROGEN', 'Водородный')], default='GASOLINE', max_length=15, verbose_name='Тип двигателя')),
                ('engine_power', models.PositiveIntegerField()),
                ('engine_volume', models.PositiveIntegerField()),
                ('transmission_type', models.CharField(choices=[('MANUAL', 'Механическая'), ('AUTOMATIC', 'Автоматическая'), ('SEMI_AUTOMATIC', 'Полуавтоматическая'), ('CVT', 'Вариатор'), ('DUAL_CLUTCH', 'Роботизированная (двойное сцепление)')], default='AUTOMATIC', max_length=20, verbose_name='Тип коробки передач')),
                ('release_year', models.IntegerField()),
                ('color_type', models.CharField(choices=[('WHITE', 'Белый'), ('BLACK', 'Чёрный'), ('SILVER', 'Серебристый'), ('GREY', 'Серый'), ('BLUE', 'Синий'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('YELLOW', 'Жёлтый'), ('ORANGE', 'Оранжевый'), ('BROWN', 'Коричневый'), ('GOLD', 'Золотой'), ('PURPLE', 'Фиолетовый')], default='BLACK', max_length=20, verbose_name='Цвет автомобиля')),
                ('number_of_seats', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='Количество сидений')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car_brand')),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car_model')),
            ],
        ),
    ]
